name: Build & Deploy

on:
  # pull_request:
  #   branches: ["master"]
  push:
    branches: ["master"]

env:
  REGISTRY: ghcr.io
  CAPROVER_HOST: https://captain.fsmdemo.fullstack.market/

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./backend/Dockerfile
            image: ghcr.io/uygarbayer/auth-system-backend
            appname: auth-system-backend
            context: ./backend
          - dockerfile: ./frontend/Dockerfile
            image: ghcr.io/uygarbayer/auth-system-frontend
            appname: auth-system-frontend
            context: ./frontend
    
    steps:
      - name: Print matrix image
        run: echo ${{ matrix.image }}
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to github packages
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Print steps.meta.outputs.tags
        run: echo ${{ steps.meta.outputs.tags }}
      
      - name: Deploy to caprover host
        uses: floms/action-caprover@bc835272f3c1ec1a470d80d44fc2a4518eb85d9d
        with:
          host: ${{ env.CAPROVER_HOST }}
          app: ${{ matrix.image }}
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          image: ${{ steps.meta.outputs.tags }}

  