name: Build and Deploy

on:
  # pull_request:
  #   branches: ["master"]
  push:
    branches: ["master"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CAPROVER_HOST: https://captain.fsmdemo.fullstack.market/
  CAPROVER_APP: auth-system-backend
  CONTEXT: ./backend
  DOCKERFILE: ./backend/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to github packages
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Image name
        run: echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}      

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to caprover host
        uses: floms/action-caprover@bc835272f3c1ec1a470d80d44fc2a4518eb85d9d
        with:
          host: ${{ env.CAPROVER_HOST }}
          app: ${{ env.CAPROVER_APP }}
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          image: ${{ steps.meta.outputs.tags }}

  