name: Build & Deploy

on:
  # pull_request:
  #   branches: ["master"]
  push:
    branches: ["master"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CAPROVER_HOST: https://captain.fsmdemo.fullstack.market/
  CAPROVER_BACKEND_APP: "${{ github.repository }}-backend"
  CAPROVER_FRONTEND_APP: "${{ github.repository }}-frontend"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./backend/Dockerfile
            image: ${{ env.REGISTRY }}/${{ env.CAPROVER_BACKEND_APP }}
            appname: backend
          - dockerfile: ./frontend/Dockerfile
            image: ghcr.io/uygarbayer/auth-system-fe
            appname: frontend
    
    steps:
      - name: Print backend name
        run: echo ${{ env.CAPROVER_BACKEND_APP }}
      
      - name: Print frontend name
        run: echo ${{ env.CAPROVER_FRONTEND_APP }}

      - name: Print matrix image
        run: echo ${{ env.REGISTRY }}/${{ env.CAPROVER_BACKEND_APP }}
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # - name: Log in to github packages
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}